# Encrypted DNS via dnscrypt-proxy (DoH) - adapted from ang3lo-azevedo
{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (lib) mkEnableOption mkIf mkForce;
  cfg = config.modules.services.dnscrypt;
in
{
  options.modules.services.dnscrypt.enable = mkEnableOption "encrypted DNS via dnscrypt-proxy (DoH)";

  config = mkIf cfg.enable {
    services.dnscrypt-proxy = {
      enable = true;
      settings = {
        # Listen on localhost so systemd-resolved can forward queries here
        listen_addresses = [ "127.0.0.1:53" "[::1]:53" ];

        # Both are DoH (HTTPS on 443), no-log, no-ECS.
        # Quad9: Swiss non-profit, good for gaming
        # Mullvad: fallback, different jurisdiction
        server_names = [ "quad9-doh-ip4-port443-filter-pri" "quad9-doh-ip6-port443-filter-pri" "mullvad-doh" ];

        require_dnssec = true;
        require_nolog = true;
        require_nofilter = false;

        # Fetch and cache the public list of verified DNS resolvers
        sources.public-resolvers = {
          urls = [
            "https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md"
            "https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md"
          ];
          cache_file = "/var/lib/dnscrypt-proxy/public-resolvers.md";
          minisign_key = "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3";
          refresh_delay = 72;
        };
      };
    };

    services.resolved = {
      enable = true;
      settings.Resolve = {
        DNSSEC = "off";
        DNSOverTLS = "no";
        Domains = "~."; # all
        DNS = "127.0.0.1";
        FallbackDNS = "9.9.9.9";
      };
    };


    networking.networkmanager = mkIf config.networking.networkmanager.enable {
      # Stop NM from pushing DHCP nameservers, which would bypass dnscrypt-proxy
      dns = mkForce "none";

      # dns=none stops NM from writing resolv.conf but NM still pushes per-link DNS to
      # resolved via D-Bus. Revert it immediately after each connection so the only DNS
      # resolver is the global 127.0.0.1 → dnscrypt-proxy.
      dispatcherScripts = [
        {
          type = "basic";
          source = lib.getExe (pkgs.writeShellApplication {
            name = "90-clear-per-link-dns";
            runtimeInputs = [ pkgs.systemd ];
            text = ''
              case "$2" in
                up|dhcp4-change|dhcp6-change)
                  resolvectl revert "$1"
                  ;;
              esac
            '';
          });
        }
      ];
    };

    # fix the "99-ethernet-default-dhcp" auto-generated by networking.useDHCP
    systemd.network.networks."99-ethernet-default-dhcp" = mkIf config.networking.useNetworkd {
      dhcpV4Config.UseDNS = false;
      dhcpV6Config.UseDNS = false;
    };

    # Delay dnscrypt-proxy until the clock is synced: it verifies TLS certificates
    # when downloading the resolver list, which fails if the clock is wrong at boot.
    systemd.services.dnscrypt-proxy = {
      after = [ "time-sync.target" ];
      wants = [ "time-sync.target" ];
    };
  };
}