# Generate using `nixos-generate-config --show-hardware-config`
# TODO generate this config
# Currently using a dummy config from a virtual machine (vmware)

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "mptspi"
    "uhci_hcd"
    "ahci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-0b653f71-7f89-4f6d-8369-bf2c79d82b1f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-0b653f71-7f89-4f6d-8369-bf2c79d82b1f".device =
    "/dev/disk/by-uuid/0b653f71-7f89-4f6d-8369-bf2c79d82b1f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7E57-989B";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/76269d67-8bbb-450a-8b00-3f60b2332541"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
