# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-91fe4c23-ba94-4e06-9f8b-4e7b936afebb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-91fe4c23-ba94-4e06-9f8b-4e7b936afebb".device = "/dev/disk/by-uuid/91fe4c23-ba94-4e06-9f8b-4e7b936afebb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0F8D-8A84";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a6a2d257-41a7-497c-a570-3dd49a428b22"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
